apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: huhuta/node-lirc
deploy:
  kubectl:
    manifests:
      - k8s-*
#profiles:
#  - name: gcb
#    build:
#      googleCloudBuild:
#        projectId: k8s-skaffold
